private_3:
  spec:
    base_os: "ubuntu"
    base_version: "v14.04"
    keypair: "{{ keypair_name }}"
    security_group: "private-3"
    instance_type: "t2.nano"
    instance_profile_name: "profile-private-3"
    instance_tags: &TAGS
      Group: "private-3"
      Type: "data"
      Environment: "production"
  cluster:
    - count: 1
      subnet_id: "{{ vpc_private_subnet_3_A.subnet.id }}"
      instance_tags:
        AvailabilityZone: A
        <<: *TAGS
    - count: 1
      subnet_id: "{{ vpc_private_subnet_3_B.subnet.id }}"
      instance_tags:
        AvailabilityZone: B
        <<: *TAGS
