public_1:
  spec:
    base_os: "ubuntu"
    base_version: "v14.04"
    keypair: "{{ keypair_name }}"
    security_group: "public-1"
    instance_type: "t2.nano"
    instance_profile_name: "profile-public-1"
    instance_tags: &TAGS
      Group: "public-1"
      Type: "web"
      Environment: "production"
  cluster:
    - count: 1
      subnet_id: "{{ vpc_public_subnet_1_A.subnet.id }}"
      instance_tags:
        AvailabilityZone: A
        <<: *TAGS
    - count: 1
      subnet_id: "{{ vpc_public_subnet_1_B.subnet.id }}"
      instance_tags:
        AvailabilityZone: B
        <<: *TAGS
