- name: Reading AMI database
  include_vars: "ami.yml"

- name: Reading public_1_cluster metadata
  include_vars: "cluster/public_1.yml"

- name: Check base AMI-ID for Ubuntu 14.04
  debug:
    msg: "{{ ami[public_1.spec.base_os][public_1.spec.base_version].ami_id }}"

- name: Launch public-1 cluster instances
  ec2:
    key_name: "{{ public_1.spec.keypair }}"
    group: "{{ public_1.spec.security_group }}"
    instance_type: "{{ public_1.spec.instance_type }}"
    image: "{{ ami[public_1.spec.base_os][public_1.spec.base_version].ami_id }}"
    wait: yes
    exact_count: "{{ item.count }}"
    count_tag: "{{ item.instance_tags }}"
    instance_profile_name: "{{ public_1.spec.instance_profile_name }}"
    instance_tags: "{{ item.instance_tags }}"
    monitoring: yes
    vpc_subnet_id: "{{ item.subnet_id }}"
  with_items: public_1.cluster
  register: ec2_cluster_public_1_result

- name: Setting ec2_cluster_public_1_result
  debug:
    var: item
  with_flattened:
    - "{{ ec2_cluster_public_1_result.results|map(attribute='tagged_instances')|list }}"
  register: ec2_cluster_public_1_result_tmp
  no_log: True

- set_fact:
    ec2_cluster_public_1: "{{ ec2_cluster_public_1_result_tmp.results|map(attribute='item')|list }}"

- name: ec2-cluster-public-1
  debug:
    var: ec2_cluster_public_1
